### ISSUE TITLE
Gathering feedback from companies.

### ISSUE THREAD

**Issue by mikeal** [nodejs/roadmap#13]
We have a lot of great feedback from developers and community members and I'm confident that we can continue to find even better ways of continuing that effort to create a living roadmap. While some of the feedback we're getting is about production use and usage within companies I don't think the public calls for feedback do a good enough job at getting information about problems at large production use.

I'd like to being seeking out large scale use cases and interviewing people there about their biggest problems. Now, the problem here is that I don't think they will be honest if their feedback, along with their name and company affiliation, is made public. These people care about Node, they don't want to disparage it, and the last thing we want as a project is some silly tech press article about "companies unhappy with Node."

The best way to do this might be to get a list of companies together we want to talk to and conduct interviews, then summarize that feedback in to a generalized document about all the companies we spoke to so that no individual complaint or problem can be directly associated with a company or individual.
### Enterprises
- [ ] Netflix
- [ ] Walmart
- [ ] Uber
- [ ] Paypal
- [ ] IBM
- [ ] Google
- [ ] Yahoo
- [ ] Microsoft
- [ ] Alibaba
### Startups
- [ ] Automattic
- [ ] Storify
- [ ] Voxer
- [ ] New Relic
- [ ] Nodejitsu
- [ ] Engine Yard
- [ ] Heroku
- [ ] AppNeta
- [ ] Skycatch
- [ ] Mapbox
### Consulting and Services

Focusing on companies working big Node users as a proxy for feedback.
- [ ] Nearform
- [ ] Strongloop
- [ ] NPM
- [ ] Node Source
- [ ] Emerging Technology Advisors
- [ ] andYet
- [ ] Modulus

**Comment by mikeal** [comment]
Feel free to suggest companies if you know of a good contact there. The initial list is mostly just companies I could think of where I know someone.

**Comment by fengmk2** [comment]
+ Alibaba

We @dead_horse @jacksontian are working on alibaba.

**Comment by mikeal** [comment]
@fengmk2 awesome! who should I email over there?

**Comment by Qard** [comment]
AppNeta

I write the node instrumentation, and our frontend people use node for tooling. Feel free to email me sbelanger@appneta.com.

**Comment by JacksonTian** [comment]
@mikeal feel free to email me shyvo1987@gmail.com. I do some research with node core, v8, etc.

**Comment by fengmk2** [comment]
Email @jacksontian please :)

**Comment by mikeal** [comment]
Preliminary emails have been sent, waiting on feedback and in some cases a list of the best contacts within companies to reach out to.

**Comment by fibric** [comment]
What about https://modulus.io/

They already talked about io.js here: http://blog.modulus.io/iojs-what-it-means-for-you

**Comment by springmeyer** [comment]
@mikeal - I can be the contact for [Mapbox](https://www.mapbox.com) | dane@mapbox.com. Since we maintain > 15 node C++ addons, and package them all as binaries for production deployment with https://github.com/mapbox/node-pre-gyp I'm interested in the roadmap for binary deployment.

**Comment by mikeal** [comment]
Added mapbox and modulus. I'll be getting in touch soon @springmeyer and I'll just talk to the Modulus folks in person later tonight at their Node Summit party :)

**Comment by fibric** [comment]
modulus :+1:

**Comment by emkay** [comment]
@mikeal did you get a contact at Yahoo?

**Comment by davglass** [comment]
@emkay Of course he did :smile:

**Comment by emkay** [comment]
@davglass :+1:

**Comment by opus13** [comment]
Auttomatic is still considered a startup?

**Comment by jasonwilliams200OK** [comment]
/copy @shanselman, @ahejlsberg, @madskristensen, @jaredpar, @nguerrera, @NTaylorMullen (and whoever is missing) 
:bulb: :bell:

**Comment by Trott** [comment]
Closing all issues in this archived repository.
