### ISSUE TITLE
Testing of npm modules

### ISSUE THREAD

**Issue by ivanwills** [nodejs/roadmap#35]
Don't know if this is the best place to bring this up but one thing that should be thought about node/iojs don't have that I miss from Perl's CPAN ecosystem is CPANTesters. Where there is some infrastructure for people to donate computer resources to run tests for modules. Reports are sent to a central location and module developers can find any issues that their modules may encounter on other systems.

I think some sort of work could be done for iojs to work in that direction.

**Comment by TheAlphaNerd** [comment]
Since CITGM does this could we perhaps close this issue?
