### ISSUE TITLE
Opt-in feedback reports

### ISSUE THREAD

**Issue by kevinmartin** [nodejs/roadmap#4]
I think a great idea is an opt-in feedback report to improve the platform. This is usually found in higher-level apps like your browser, but I think it could help us out, as well.

These reports can, if implemented correctly, help find memory leaks or bugs in the codebase.

Upon installation, ask the user to send these feedback reports. They would be sent whenever there is a slow period on the system and never in high load.

**Comment by jbergstroem** [comment]
I like the idea. Make it an optional (open sourced) npm module that people can install; suggest it only being run in production (with examples to avoid dev mode such as env vars) and elaborate on how it works, how it contributes to the iojs and how it as a result benefits that specific user.

I think the most interesting statistics would come from "hot paths"; most common requires, gc, memory allocation and similar. Find usage patterns and make them faster. As long as its always developed and distributed as open source I think experienced developers understand the benefits for sharing their information to this module.

**Comment by jbergstroem** [comment]
Being part of the build-wc, just getting basic info such as os, iojs version and its built state (read: how did it get installed) would be very valuable information (which @rmg already pointed out :).

**Comment by Trott** [comment]
Closing all issues in this archived repository.
