### ISSUE TITLE
html from markdown

### ISSUE THREAD

**Issue by jldec** [nodejs/roadmap#49]
Hi Mikeal (et al)

I have been experimenting with a solution to make translations and updates to the io.js roadmap presentation easier.

The idea is to use [markdown](https://github.com/jldec/roadmap/tree/master/markdown) for the source, and generate HTML for publishing on gh-pages.

The solution uses 2 branches (master and gh-pages) and a subtree merge to publish files from the /gh-pages directory in the master branch into the root of the gh-pages branch.

You can see everything in the fork at https://github.com/jldec/roadmap

The published output is at http://jldec.github.io/roadmap

(robots.txt is disallowing search engines from crawling that copy of the roadmap site). 

There is also a new [CONTRIBUTING.md](https://github.com/jldec/roadmap/blob/master/CONTRIBUTING.md) with more detailed instructions.

I would be happy to provide support for the [pub-server](https://github.com/jldec/pub-server) tool which generates the HTML from markdown. 

pub-server is a pure javascript/node/npm static site generator and web-CMS based on markdown - no database required.

If you think this would help, let me know. I think you need to create a master branch in your repo before i can send you PRs for the two branches.

hth
Jürgen Leschner (github/jldec)

**Comment by Trott** [comment]
Closing all issues in this archived repository.
