### ISSUE TITLE
What, if any part does this roadmap have in light of the merger?

### ISSUE THREAD

**Issue by benjamingr** [nodejs/roadmap#50]
Is this going to be re-branded with node since the goals still stand? Is it going to be removed? Rewritten?

**Comment by mikeal** [comment]
The working group will remain and, after the merge, we'll kick off a new thread to update the roadmap. A lot of what is in the current roadmap has been completed so it needs some revising.

**Comment by benjamingr** [comment]
Roger, thanks.

**Comment by tmn** [comment]
Any point in translating it as it is today?

**Comment by mikeal** [comment]
Probably best to wait.

**Comment by mhdawson** [comment]
Not sure this is the best place to ask but once the effort to update the roadmap starts i'd like to be involved.
