### ISSUE TITLE
Community polling program

### ISSUE THREAD

**Issue by mikeal** [nodejs/roadmap#53]
Twitter has a new poll feature that think we can use to effectively get input from the broader community.

If we design a series of simple polls to answer specific questions we can inform the direction of the project.

Twitter polls have some obvious limitations. You get a small amount of text along with two selectable answers.

Let's put together some ideas for questions we'd like to answer.

/cc
- @nodejs/tsc
- @nodejs/evangelism

**Comment by mikeal** [comment]
*Which Node.js version are you planning on migrating to?*

* Node.js v4
* Node.js v5

**Comment by bnb** [comment]
_Will you write your modules to be compatible with LTS releases?_

* Yes
* No

**Comment by julianduque** [comment]
Do you use NAN for your Native Modules?
* Yes
* No

**Comment by Fishrock123** [comment]
Do you understand our versioning scheme?
- No
- (No)

Ok just kidding, it's just a yes/no question. Maybe the question needs better wording.

**Comment by julianduque** [comment]
What version of npm do you use?
* npm@2
* npm@3

**Comment by Trott** [comment]
Maybe we can get specific here about what we'd be trying to determine with these polls. Thinking of questions is pretty easy, but thinking of questions where the answers will tell us something useful is more challenging.

To use the example question, if we find out that (making this up, of course) 58% of users plan on using Node 4 LTS for the foreseeable future and 42% plan on using Node 5 Stable, how does this information inform decisions by the project? (Especially considering that the information will likely be out of date very quickly!)

Here are some things that I think might be useful to try to ascertain. (It may be difficult to word some or all of these for a Twitter poll, but that doesn't mean it's not worth trying.)

* For anyone *not* using Node v4 or v5, what is keeping them from updating? How can the project make it easier (or more irresistible) to update?

* Where do you get your Node news? What can the Evangelism WG do to get their message more in your inbox, social media streams, whatever?

* For anyone who would like to be involved in the Node project itself but isn't, what is stopping you?

**Comment by Qard** [comment]
Are you one of the limited subset of node users who uses Twitter?

- Yes
- How even do I answer this?

Seriously though, I'd ask about what the community feels the direction and priorities should be: performance vs usability, runtime error recovery vs post-mortem debugging, lower-level vs higher-level API, etc.

**Comment by mikeal** [comment]
@Qard the nodejs twitter account has 284K followers, so we can reach more people there than we can with any other medium.

**Comment by Trott** [comment]
Closing all issues in this archived repository.
