### ISSUE TITLE
Notifications for TC meetings.

### ISSUE THREAD

**Issue by tracker1** [nodejs/roadmap#7]
Just a suggestion, should have a notification list (meetup?) for the TC meetings, so that those that want to participate that aren't in core, can at least add it to their calendars, and have reminders etc.

**Comment by rvagg** [comment]
I've been creating issues in iojs/io.js for TC meetings, such as https://github.com/iojs/io.js/issues/230 for the next one. I'm not sure a mailing list is the right way to go about it but we could set up an io.js calendar that anyone can subscribe to.

For now, I'd suggest following myself and/or @mikeal on Twitter to get notifications about upcoming meetings.

Also, +1 to @bnoordhuis's suggestion of participating in #io.js, most of the TC members are there and are usually watching what's going on there and sometimes discussion spills into the meetings.

**Comment by rvagg** [comment]
Created an io.js calendar you can add to your own calendar, details here: https://github.com/iojs/io.js/issues/230#issuecomment-68507813

**Comment by mikeal** [comment]
Now that we have a Google+ page where we do all the TC and WG meetings we also have G+ notifications and a calendar.

What other notifications do we want to see? We can automated them fairly easily now that we have the calendar.

**Comment by bnb** [comment]
Sorry to necropost, but have you set up the calendar so you can add TC/WG meetings when they're scheduled? Do you have any more ideas for what you can put on a calendar?

**Comment by mikeal** [comment]
I have no idea how the access controls are handled or anything like that, maybe we should do a new post on the evangelism site to cover what we can do around this.

**Comment by Trott** [comment]
Closing all issues in this archived repository.
