### ISSUE TITLE
Building node as a shared library instead of an executable

### ISSUE THREAD

**Issue by kobalicek** [nodejs/roadmap#9]
I think that there should be something like `libnode.so` or `node.dll` and `node` executable which simply calls an entry point in the shared object. Then, C++ addons can simply link to a library instead of linking to an executable.

What do you guys think about this?

I remember that there was an option in gyp for that, but all distributions use the executable-only model and I remember the option didn't work out for me even in the past.

I think that node can be used for much more things than just writing servers and having a model that other applications can use seems important. I really think that node can be embedded in other applications. It would be interesting to see more native addons wrapping other libraries and also native addons depending on other native addons (is this possible today?).

Thanks

**Comment by bnoordhuis** [comment]
I'm afraid I don't have time to summarize it but see joyent/node#7336 for background; the short version is that it's not that simple (unfortunately.)

**Comment by kobalicek** [comment]
Thanks, interesting discussion.

I think that in such case node shouldn't allow to register custom constructions when building node itself, this responsibility can be moved out and people embedding node would just:

  1. Create the environment
  2. Register modules
  3. Use the environment

The problem I see is that if I create two node addons they export the same symbol. This can be fixed by introducing a naming schema, so for example if the addon is called `myaddon` the initializer would be something like `node_myaddon_init` exported as "C". In that case it would be just fixing the loader to hook up the right symbol based on the shared object name, and moving the responsibility on the embedder to call that function when creating the environment.

Well, I think that I see it simpler than it actually is, but I also think this can be fixed.

**Comment by rvagg** [comment]
It's kind of sad that it was dropped from joyent/node, this is an interesting concept and could be a good addition to the roadmap, it could be great for expanding Node's reach. If there are technical problems then perhaps they can be dealt with simply by limiting the scope of what a shared library is actually able to do. I fear that some of the objection to landing this feature is mostly about waiting for Node internals to be perfect.

@kobalicek (and others), could you outline some of the use-cases you imagine for this?

**Comment by Qard** [comment]
That "perfect" certainly deserves some quotation marks. I don't think the node codebase will ever fully escape the current hackiness.

**Comment by rvagg** [comment]
@Qard indeed and it should be embraced lest we be crippled by it and have trouble getting simple releases out the door ... >cough<

**Comment by Qard** [comment]
Agreed. The pursuit of a clean and friendly codebase is a noble cause, but not at the expense of progress. :)

**Comment by kobalicek** [comment]
Basically, I would like to see node as a runtime rather than application. For me it would be really interesting to create a native C++ addon for UI and experiment with doing some UI stuff with node. I mean, I don't see it worse to ship some app with libnode instead of libQt.

I'm working on a vector graphics library (blend2d.com) and I have a working node addon, would be nice if it can be used for more than some server image processing in the future ;) However, I see that maybe node is not a right choice for these kind of experiments. I myself see the whole addon system a bit hacky.

But, my question remains, is it possible to create a node addon that depends on or extends another addon?

**Comment by kobalicek** [comment]
Guys how can I help with this? I'm still definitely interested of having node as a shared library by default.

**Comment by bnoordhuis** [comment]
@kobalicek I think the following practical issues need to be resolved:

1. Fix auto-registration of built-in native modules.

2. Make the build type for the 'iojs' target in node.gyp configurable, it's always 'executable' now.

3. Add `--enable-static` and `--enable-shared` switches to the configure script.

4. Fix the build system so it can build static and shared libraries at the same time (nice to have, not mandatory.)  Perhaps it's possible to define an iojs_base target that's depended on by iojs_static and iojs_shared targets.

We can evolve the API as the need arises.

**Comment by mhart** [comment]
Does https://github.com/iojs/io.js/pull/1341 now close this?

**Comment by bnoordhuis** [comment]
@mhart Not yet.  You can build io.js as a static library now but not a shared library.  It may be as easy as setting node_target_type to 'shared_library' but I haven't tested that.

**Comment by mhdawson** [comment]
@bnoordhuis to fully close would we include delivering shared libraries as part of the binary drops ? Is that part of what you mean for "Fix the build system" above ?

**Comment by bnoordhuis** [comment]
@mhdawson That wasn't my intention.  If building as a shared library works and the resulting .so is usable(ish), I'm happy.

**Comment by mhdawson** [comment]
@bnoordhuis understood.  Has there been any prior discussion of whether we should ship shared libraries in addition to the binaries ?

**Comment by kobalicek** [comment]
I think it should be either static or shared, but not both.

**Comment by bnoordhuis** [comment]
> Has there been any prior discussion of whether we should ship shared libraries in addition to the binaries ?

Not to my knowledge.

**Comment by mhdawson** [comment]
@kobalicek why only one or the other ?   There are advantages/disadvantages to both

**Comment by kobalicek** [comment]
@mhdawson I think it's always good to avoid diversity, can't imagine how native modules will deal with this. I think the biggest example is what happened in io.js that just used different "node" name.

**Comment by mhdawson** [comment]
It looks like the changes required to support a shared library are along these lines:

**Comment by mhdawson** [comment]
@kobalicek are there some specific issues that you think would be different between a static library versus shared so that I can better understand ?

**Comment by kobalicek** [comment]
I think there can be only build issues of native modules, I'm not sure how node-gyp handles this, but I know I have to use `pangyp` when building my addons for io, so yeah, I think this can happen also here.

**Comment by mhdawson** [comment]
@kobalicek are these issues different between using a shared library and a static one ?  Do you have a test case that shows one ? 

@bnoordhuis what's your take on doing static, shared or both ?

**Comment by mhdawson** [comment]
I'm hoping we can get back to this.  I think the next step is that we prepare a Pull request adding support for shared libraries and we can discuss there.

**Comment by davedoesdev** [comment]
This is at a slight tangent but I've been building a `libnode.so` for [OSv](http://osv.io/) for a while:

https://github.com/cloudius-systems/osv-apps/tree/master/node

It works fine.

**Comment by vroad** [comment]
libnode.so builds and works on Android, but some manual adjustments were needed. (https://github.com/nodejs/node/issues/3074).

**Comment by drom** [comment]
Any progress on this front?

**Comment by yan-foto** [comment]
If I'm not totally mistaken, GitHub's Electron does something like this. You can find `libnode.so` in the released archive of Electron. They have their own [fork](https://github.com/electron/node) of node. Also take a look [here](https://github.com/electron/electron/commit/a400bb59973cc9c606c53c83c2699783667d438a).

**Comment by ChALkeR** [comment]
@yan-foto Btw, that's more like a patchset than a fork — it's 19 commits (doing various things) re-applied on top of Node.js on Node.js releases. It's synced with 6.1.0 now.

**Comment by ChALkeR** [comment]
Ah, also see https://github.com/nodejs/node-v0.x-archive/pull/6744 and https://github.com/electron/node/issues/2.

**Comment by mhdawson** [comment]
See https://github.com/nodejs/node/pull/6994 for current work.  I'm hoping we can get this in as the first step in the next few weeks.

**Comment by Trott** [comment]
Closing all issues in this archived repository.
